"""change to game model

Revision ID: 0b6dac8dbfe1
Revises: 91472a285194
Create Date: 2025-01-05 00:57:14.341512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6dac8dbfe1'
down_revision = '91472a285194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winner_loser_prop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_one', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('option_two', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winner_loser_prop', schema=None) as batch_op:
        batch_op.drop_column('option_two')
        batch_op.drop_column('option_one')

    # ### end Alembic commands ###
