"""Add anytime TD scorer prop tables

Revision ID: 0c34d734c3fc
Revises: fix_prop_limit_2026
Create Date: 2026-01-19 16:33:07.338076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c34d734c3fc'
down_revision = 'fix_prop_limit_2026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anytime_td_prop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('correct_answer', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anytime_td_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=False),
    sa.Column('prop_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['prop_id'], ['anytime_td_prop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anytime_td_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=200), nullable=False),
    sa.Column('td_line', sa.Float(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('current_tds', sa.Integer(), nullable=True),
    sa.Column('anytime_td_prop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anytime_td_prop_id'], ['anytime_td_prop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anytime_td_option')
    op.drop_table('anytime_td_answer')
    op.drop_table('anytime_td_prop')
    # ### end Alembic commands ###
