"""auth stuff?

Revision ID: 1cba82563f2c
Revises: 54cdafdc96d0
Create Date: 2025-06-23 21:54:58.826681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cba82563f2c'
down_revision = '54cdafdc96d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hash_map_answers', schema=None) as batch_op:
        batch_op.alter_column('answer_points',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hash_map_answers', schema=None) as batch_op:
        batch_op.alter_column('answer_points',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
