"""Create table

Revision ID: 205175c4bee3
Revises: 
Create Date: 2024-12-28 19:34:46.309480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205175c4bee3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create `user` table
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=75), nullable=False),
        sa.Column('password', sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )

    # Create `league` table
    op.create_table(
        'league',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('league_name', sa.String(length=128), nullable=True),
        sa.Column('join_code', sa.String(length=30), nullable=True),
        sa.Column('commissioner_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['commissioner_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('join_code'),
        sa.UniqueConstraint('league_name')
    )

    # Create `player` table
    op.create_table(
        'player',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=75), nullable=False),
        sa.Column('league_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['league_id'], ['league.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # Drop the old `users` table
    # op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop `player` table first, as it references `league` and `user`
    op.drop_table('player')

    # Drop `league` table next, as it references `user`
    op.drop_table('league')

    # Drop `user` table last
    op.drop_table('user')

    # Recreate the old `users` table
    op.create_table(
        'users',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('username', sa.VARCHAR(length=75), autoincrement=False, nullable=False),
        sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='users_pkey'),
        sa.UniqueConstraint('username', name='users_username_key')
    )
    # ### end Alembic commands ###

