"""variable options

Revision ID: 28d1e5b19427
Revises: 2e0da5db7dfc
Create Date: 2025-01-25 18:31:02.744559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28d1e5b19427'
down_revision = '2e0da5db7dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hash_map_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_choice', sa.String(length=100), nullable=True),
    sa.Column('answer_points', sa.Integer(), nullable=True),
    sa.Column('prop_id', sa.Integer(), nullable=True, foreign_keys=['variable_option_prop.id']),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variable_option_prop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('correct_answers', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variable_option_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=100), nullable=True),
    sa.Column('prop_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['prop_id'], ['variable_option_prop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variable_option_answer')
    op.drop_table('variable_option_prop')
    op.drop_table('hash_map_answers')
    # ### end Alembic commands ###
