"""variable options

Revision ID: 3cdee6a18c51
Revises: 28d1e5b19427
Create Date: 2025-01-25 18:33:31.051225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cdee6a18c51'
down_revision = '28d1e5b19427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hash_map_answers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'variable_option_prop', ['prop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hash_map_answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
