""".

Revision ID: 41c2d89e964e
Revises: db425e65cccf
Create Date: 2025-01-26 15:08:13.939285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c2d89e964e'
down_revision = 'db425e65cccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hash_map_answers', schema=None) as batch_op:
        batch_op.alter_column('answer_points',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hash_map_answers', schema=None) as batch_op:
        batch_op.alter_column('answer_points',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
