"""added graded field

Revision ID: 46de918c7737
Revises: 6a3c6e447e6d
Create Date: 2025-01-09 00:53:59.738835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46de918c7737'
down_revision = '6a3c6e447e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graded', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('graded')

    # ### end Alembic commands ###
