"""Add auth_provider column to User table

Revision ID: 54cdafdc96d0
Revises: 41c2d89e964e
Create Date: 2025-06-14 21:03:42.331447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54cdafdc96d0'
down_revision = '41c2d89e964e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hash_map_answers', schema=None) as batch_op:
        batch_op.alter_column('answer_points',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=20), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('auth_provider')

    with op.batch_alter_table('hash_map_answers', schema=None) as batch_op:
        batch_op.alter_column('answer_points',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    # ### end Alembic commands ###
