"""game and prop stuff

Revision ID: 5c566a1fdbe6
Revises: 24dc76d5057e
Create Date: 2025-01-04 02:16:50.958855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c566a1fdbe6'
down_revision = '24dc76d5057e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('game_name', sa.String(length=200), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('over_under_prop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=200), nullable=True),
    sa.Column('over_points', sa.Integer(), nullable=True),
    sa.Column('under_points', sa.Integer(), nullable=True),
    sa.Column('correct_answer', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('winner_loser_prop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=200), nullable=True),
    sa.Column('winner_points', sa.Integer(), nullable=True),
    sa.Column('loser_points', sa.Integer(), nullable=True),
    sa.Column('correct_answer', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winner_loser_prop')
    op.drop_table('over_under_prop')
    op.drop_table('game')
    # ### end Alembic commands ###
