"""add_polling_and_live_stat_fields

Revision ID: 610b908d4488
Revises: 1cba82563f2c
Create Date: 2025-12-26 15:14:43.000903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610b908d4488'
down_revision = '1cba82563f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_game_id', sa.String(length=100), nullable=True))
        # Add boolean columns as nullable first, then set defaults and make not null
        batch_op.add_column(sa.Column('is_polling', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('team_a_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team_b_score', sa.Integer(), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE game SET is_polling = FALSE WHERE is_polling IS NULL")
    op.execute("UPDATE game SET is_completed = FALSE WHERE is_completed IS NULL")

    # Now make them NOT NULL
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('is_polling', nullable=False)
        batch_op.alter_column('is_completed', nullable=False)

    with op.batch_alter_table('over_under_prop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('player_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stat_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('line_value', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('current_value', sa.Numeric(), nullable=True))

    with op.batch_alter_table('winner_loser_prop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_a_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('team_b_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('team_a_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('team_b_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('team_a_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team_b_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('winning_team_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winner_loser_prop', schema=None) as batch_op:
        batch_op.drop_column('winning_team_id')
        batch_op.drop_column('team_b_score')
        batch_op.drop_column('team_a_score')
        batch_op.drop_column('team_b_name')
        batch_op.drop_column('team_a_name')
        batch_op.drop_column('team_b_id')
        batch_op.drop_column('team_a_id')

    with op.batch_alter_table('over_under_prop', schema=None) as batch_op:
        batch_op.drop_column('current_value')
        batch_op.drop_column('line_value')
        batch_op.drop_column('stat_type')
        batch_op.drop_column('player_id')
        batch_op.drop_column('player_name')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('team_b_score')
        batch_op.drop_column('team_a_score')
        batch_op.drop_column('is_completed')
        batch_op.drop_column('is_polling')
        batch_op.drop_column('external_game_id')

    # ### end Alembic commands ###
