"""adding answer model - rough draft

Revision ID: 6a3c6e447e6d
Revises: 85bf05e04679
Create Date: 2025-01-05 03:05:56.593405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3c6e447e6d'
down_revision = '85bf05e04679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('over_under_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=256), nullable=True),
    sa.Column('prop_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['prop_id'], ['over_under_prop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('winner_loser_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=256), nullable=True),
    sa.Column('prop_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['prop_id'], ['winner_loser_prop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winner_loser_answer')
    op.drop_table('over_under_answer')
    # ### end Alembic commands ###
