"""Add PlayerPropSelection model and prop_limit to Game

Revision ID: 7f71240d9d35
Revises: 610b908d4488
Create Date: 2026-01-13 16:06:09.027637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f71240d9d35'
down_revision = '610b908d4488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_prop_selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('prop_type', sa.String(length=50), nullable=False),
    sa.Column('prop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', 'prop_type', 'prop_id', name='unique_player_prop_selection')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prop_limit', sa.Integer(), nullable=False, server_default='2'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('prop_limit')

    op.drop_table('player_prop_selection')
    # ### end Alembic commands ###
