"""Change anytime_td_option points to Float to allow decimals

Revision ID: 8517995ea8bb
Revises: 0c34d734c3fc
Create Date: 2026-02-08 18:05:48.455651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8517995ea8bb'
down_revision = '0c34d734c3fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anytime_td_option', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anytime_td_option', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
