"""game and prop stuff

Revision ID: 91472a285194
Revises: 5c566a1fdbe6
Create Date: 2025-01-04 02:20:55.126922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91472a285194'
down_revision = '5c566a1fdbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winner_loser_prop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('underdog_points', sa.Integer(), nullable=True))
        batch_op.drop_column('winner_points')
        batch_op.drop_column('loser_points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winner_loser_prop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loser_points', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('winner_points', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('underdog_points')
        batch_op.drop_column('favorite_points')

    # ### end Alembic commands ###
