"""Add is_mandatory field to all prop models

Revision ID: c7b04f07f906
Revises: 7f71240d9d35
Create Date: 2026-01-13 16:47:44.005902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b04f07f906'
down_revision = '7f71240d9d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Over/Under props default to optional (False)
    with op.batch_alter_table('over_under_prop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_mandatory', sa.Boolean(), nullable=False, server_default='false'))

    # Variable Option props default to optional (False)
    with op.batch_alter_table('variable_option_prop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_mandatory', sa.Boolean(), nullable=False, server_default='false'))

    # Winner/Loser props default to mandatory (True)
    with op.batch_alter_table('winner_loser_prop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_mandatory', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winner_loser_prop', schema=None) as batch_op:
        batch_op.drop_column('is_mandatory')

    with op.batch_alter_table('variable_option_prop', schema=None) as batch_op:
        batch_op.drop_column('is_mandatory')

    with op.batch_alter_table('over_under_prop', schema=None) as batch_op:
        batch_op.drop_column('is_mandatory')

    # ### end Alembic commands ###
