"""integer to decimal scoring

Revision ID: d24e095cd4d6
Revises: 46de918c7737
Create Date: 2025-01-09 21:57:39.335038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24e095cd4d6'
down_revision = '46de918c7737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('over_under_prop', schema=None) as batch_op:
        batch_op.alter_column('over_points',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)
        batch_op.alter_column('under_points',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)

    with op.batch_alter_table('winner_loser_prop', schema=None) as batch_op:
        batch_op.alter_column('favorite_points',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)
        batch_op.alter_column('underdog_points',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winner_loser_prop', schema=None) as batch_op:
        batch_op.alter_column('underdog_points',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('favorite_points',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('over_under_prop', schema=None) as batch_op:
        batch_op.alter_column('under_points',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('over_points',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
