""".

Revision ID: db425e65cccf
Revises: 3cdee6a18c51
Create Date: 2025-01-25 22:04:36.167060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db425e65cccf'
down_revision = '3cdee6a18c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variable_option_prop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answer', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.drop_column('correct_answers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variable_option_prop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answers', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
        batch_op.drop_column('correct_answer')

    # ### end Alembic commands ###
